services:
  mc-server:
    restart: always
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      - EULA=TRUE
    volumes:
      - ./mc-data:/data

# D4nchen base - 744 91 222
