apiVersion: v1
kind: Service
metadata:
  name: mc-server-service
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: mc-server
  ports:
  - name: mc-service-tcp
    port: 25565
    hostPort: 25565
    targetPort: mc-port-tcp
    protocol: TCP
  - name: mc-service-udp
    port: 25565
    hostPort: 25565
    targetPort: mc-port-udp
    protocol: UDP